src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable:true)]
    private ?string $urlToImage = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $date_added = null;

    #[ORM\Column(length: 255)]
    private ?string $date_updated = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    

    public function geturlToImage(): ?string
    {
        return $this->urlToImage;
    }

    public function seturlToImage(?string $urlToImage): self
    {
        $this->urlToImage = $urlToImage;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateAdded(): ?string
    {
        return $this->date_added;
    }

    public function getLastUpdated(): ?string
    {
        return $this->date_updated;
    }

    public function setDateAdded(string $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function setLastUpdated(string $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function eraseCredentials()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }
}

src/Controller/NewsController.php
<?php

// src/Controller/NewsController.php
namespace App\Controller;


use App\Entity\News;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
class NewsController extends AbstractController
{
    private $em;
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }
    

    #[Route('/news', methods: ['GET'],  name: 'news_list')]
    public function list(Request $request)
    {
        $page = $request->query->get('page', 1);
        $pageSize = 10;
        $entityManager = $this->em;
        $news = $entityManager->getRepository(News::class)->findBy([], ['date_added' => 'desc'], $pageSize, ($page - 1) * $pageSize);
        $count = $entityManager->createQueryBuilder()
        ->select('COUNT(n)')
        ->from(News::class, 'n')
        ->getQuery()
        ->getSingleScalarResult();

        return $this->render('news/index.html.twig', [
            'news' => $news,
            'page' => $page,
            'pageSize' => $pageSize,
            'count' => $count,
        ]);
    }

    /**
     * @Route("/news/{id}", name="news_show")
     * @IsGranted("view", subject="news")
     */
    
    public function show(News $news)
    {
        return $this->render('news/show.html.twig', [
            'news' => $news,
        ]);
    }

    /**
     * @Route("/news/delete/{id}", name="news_delete")
     * @IsGranted("delete", subject="news")
     */
    #[Route('/news/delete/{id}', methods:['GET'], name: 'delete_news')]
    // #[Route('/news/{id}/delete', methods: ['POST'], name: 'delete_news')]
    public function delete(News $news)
    {
        $entityManager = $this->em;
        $entityManager->remove($news);
        $entityManager->flush();

        $this->addFlash('success', 'News article deleted.');

        return $this->redirectToRoute('news_list');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}News Parser{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/news/index.html.twig
{# templates/news/index.html.twig #}

{% extends 'base.html.twig' %}

{% block content %}
    {% for article in news %}
    
        <h2>{{ article.title }}</h2>
        <p>{{ article.description }}</p>
        <img src="{{ article.picture }}" height=100 width=100 alt="">
        <p>{{ article.dateAdded|date }}</p>
            <form method="post" action="{{ path('delete_news', {'id': article.id}) }}">
                <button type="submit">Delete</button>
            </form>
    {% endfor %}

    {% if count > 1 %}
        <div class="pagination">
            {% for i in 1..count %}
                <a href="{{ path('news_list', {'page': i}) }}">{{ i }}</a>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}